EscolaVirtual.Site/Controllers/CursosController.cs
using System;
using System.Web.Mvc;
using EscolaVirtual.Conteudo.Application.Interfaces;
using Microsoft.AspNet.Identity;

namespace EscolaVirtual.Site.Controllers
{
    [RoutePrefix("cursos")]
    public class CursosController : Controller
    {
        private readonly ICursoAppService _cursoAppService;

        public CursosController(ICursoAppService cursoAppService)
        {
            _cursoAppService = cursoAppService;
        }

        [Route("lista-de-cursos")]
        public ActionResult Index()
        {
            return View(_cursoAppService.ObterTodos());
        }
    }
}

EscolaVirtual.Site/Controllers/PedidosController.cs
using System;
using System.Web.Mvc;
using EscolaVirtual.Conteudo.Application.Interfaces;
using EscolaVirtual.Vendas.Application.Interfaces;
using EscolaVirtual.Vendas.Application.ViewModels;
using Microsoft.AspNet.Identity;

namespace EscolaVirtual.Site.Controllers
{
    [Authorize]
    [RoutePrefix("carrinho")]
    public class PedidosController : BaseController
    {
        private readonly ICursoAppService _cursoAppService;
        private readonly IPedidoAppService _pedidoAppService;

        public PedidosController(ICursoAppService cursoAppService, IPedidoAppService pedidoAppService)
        {
            _cursoAppService = cursoAppService;
            _pedidoAppService = pedidoAppService;
        }

        [Route("")]
        public ActionResult Index()
        {
            var pedido = _pedidoAppService.ObterPedidoPendente(AlunoId);

            return View("Carrinho", pedido);  
        }

        [Route("adicionar/{id:guid}")]
        public ActionResult AdicionarCurso(Guid id)
        {
            var curso = _cursoAppService.ObterCurso(id);

            var item = new PedidoItemViewModel()
            {
                CursoId = curso.CursoId,
                Valor = curso.Valor,
                Descricao = curso.Nome,
                Quantidade = 1
            };

            var pedido = _pedidoAppService.AdicionarPedidoItem(item, AlunoId);

            if (ValidarErrosDominio())
            {
                return View("Carrinho", pedido);
            }

            return RedirectToAction("Index");
        }
    }
}

EscolaVirtual.Site/Views/Cursos/Index.cshtml
@model IEnumerable<EscolaVirtual.Conteudo.Application.ViewModels.CursoViewModel>

@{
    ViewBag.Title = "Cursos";
}

<div>
    <h2>Lista de Cursos</h2>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <strong>@ViewBag.Title</strong>
    </div>
    <table class="table table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vagas)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>
                <td>
                    @{
                        var data = DateTime.Parse(@item.DataInicio.ToString()).ToShortDateString();
                    }
                    @Html.DisplayFor(modelItem => data)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vagas)
                </td>
                <td>
                    <a href="@Url.Action("AdicionarCurso", "Pedidos", new { id = item.CursoId })" id="@item.CursoId" class="btn btn-info"><span title="Matricular" class="glyphicon glyphicon-shopping-cart"></span></a>
                </td>
            </tr>
        }

    </table>
</div>